### ISSUE TITLE
Pretrained models checkpoints are missing

### ISSUE THREAD

**Issue by matteo-pennisi** [hcholab/k-salsa#1]
First of all thanks for the awesome work,
unfortunately checkpoints links are missing from the readme :(

https://github.com/hcholab/k-salsa/blob/beaed92288e75181f65780498f0f0578c12ab1e3/README.md?plain=1#L29-L39

**Comment by minkyujeon** [comment]
The checkpoints have been uploaded to the GitHub repository. Thanks.
